# Use container-based distribution
sudo: false
language: c++
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - re2c
            - liblua5.1-0-dev
            - zsh
            - python-yaml
before_install:
  - pip install --user cpp-coveralls
script:
  - mkdir build
  - echo "CXX = 'g++-5'" > build/debug.py
  - echo "CC = 'gcc-5'" >> build/debug.py
  - echo "CXXFLAGS = ['-std=c++11', '-O2', '-g', '-W', '-Wall', '--coverage']" >> build/debug.py
  - echo "LINKFLAGS = ['-std=c++11', '--coverage']" >> build/debug.py
  - scons -j3 && scons -j3 example cexample && scons -j3 test
after_success:
  - coveralls --include build/gcov --gcov-options '\-lp' -b ${PWD}
