# Use container-based distribution
sudo: false
language: c++
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - re2c
            - liblua5.1-0-dev
            - zsh
            - lcov
before_install:
  - gem install coveralls-lcov
script:
  - mkdir build
  - echo "CXX = 'g++-5'" > build/debug.py
  - echo "CC = 'gcc-5'" >> build/debug.py
  - echo "CXXFLAGS = ['-std=c++11', '-O2', '-g', '-W', '-Wall']" >> build/debug.py
  - echo "LINKFLAGS = ['-std=c++11']" >> build/debug.py
  - scons -j3
  - scons -j3 example cexample
  - echo "CXX = 'g++-5'" > build/debug.py
  - echo "CC = 'gcc-5'" >> build/debug.py
  - echo "CXXFLAGS = ['-std=c++11', '-O2', '-g', '-W', '-Wall', '--coverage']" >> build/debug.py
  - echo "LINKFLAGS = ['-std=c++11', '--coverage']" >> build/debug.py
  - scons -j3 test
after_success:
  - lcov --gcov-tool /usr/bin/gcov-5 --directory . --capture --output-file coverage.info
  - lcov --gcov-tool /usr/bin/gcov-5 --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --gcov-tool /usr/bin/gcov-5 --list coverage.info
  - coveralls-lcov coverage.info
